import { cssVariableValuesFormatter } from './css-variable-values';
import { testFormatter } from './test-formatter';

describe('cssVariableValuesFormatter', () => {
  const { formatArray } = testFormatter({
    formatter: cssVariableValuesFormatter,
  });

  it('should return autogenerated message with no tokens', async () => {
    const formatted = await formatArray({ allTokens: [] });

    expect(formatted).toContain(
      ' * Do not edit directly, this file was auto-generated.',
    );
  });

  it('should return css variable const with token value', async () => {
    const formatted = await formatArray({
      allTokens: [
        {
          name: 'color-gray-500',
          type: 'color',
          value: '#333333',
        },
      ],
      options: { exportName: 'consts' },
    });

    expect(formatted).toContain(`'--color-gray-500': '#333333',`);
  });
});
