name: PR Lint

permissions:
  pull-requests: read

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  validate-title:
    runs-on: ubuntu-latest
    steps:
      - uses: achieveagility/action-conventional-pr@v1
